
services:
  postgres:
    image: postgres:15
    container_name: skn-postgres
    environment:
      POSTGRES_DB: SKN
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: so
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: SKN.API/Dockerfile
    container_name: skn-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=SKN;Username=postgres;Password=so;Include Error Detail=true;
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./SKN.API:/app
      - /app/node_modules

volumes:
  postgres_data: